name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the desired Python version here
          
      - name: Install the GCloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credential: true
          

      # Other steps for building and testing the app

      - name: Log in to Docker Hub
        run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t nurbakar/hello-app:${GITHUB_SHA} -f Dockerfile .

      - name: Push Docker image
        run: docker push nurbakar/hello-app:${GITHUB_SHA}
        
      - name: Deploy to GKE
        env: 
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run:
          gcloud container clusters get-credentials project --region us-central1
          kubectl apply -f kubernetes.yaml
          
